# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/miatoll-gcam/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/AGC-Camera


PRODUCT_PACKAGES += \
    AGC-Camera
